-- Author Names: Varun Sahni, Junyuan Chen
-- File Name: initial_data.sql
-- Date and time completed: 2022-01-08 22:05
-- Assignment Name: Company Database Project
-- TODO: Insert initial data into sql


BEGIN TRANSACTION;

-- Name randomly generated from
-- https://www.behindthename.com/random/random.php
-- Phone number generated by random.randint()

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '38bd954b707eb7e32747893b525d337aa53ce4054200c352b816846627100437',
    2,
    'Waldo Ikin',
    'waldoi@waldoshoes.com',
    '(905) 123-4567',
    '2021-12-01',
    'Company Owner',
    1000000,
    NULL
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '4868d20636f227e31d2bdeb1cd6fd137b4ced117ed2869b873ba7ce468c4ad55',
    1,
    'Roswell Levitt',
    'roswelll@waldoshoes.com',
    '(303) 857-9146',
    '2021-12-10',
    'Product Development Manager',
    500000,
    1
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '201fcf76fedd59e9e282cdd95a29d4c1dae0b2387dd4f37b03be3716ee5572f4',
    1,
    'Paul Ruggles',
    'paulr@waldoshoes.com',
    '(253) 377-1346',
    '2021-12-13',
    'Marketing Department Manager',
    600000,
    1
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '26b80ca0ed3c1c9ff688780ea776d0208150ab2f6ea303517a222eea03527049',
    1,
    'Cherise Braxton',
    'cheriseb@waldoshoes.com',
    '(581) 115-8466',
    '2021-12-18',
    'IT Department Manager',
    550000,
    1
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '5eb4629a04b435025cd3a06eb7f510e32b87aca6439e903c4509969747f505bf',
    0,
    'Eleanor Haley',
    'eleanorh@waldoshoes.com',
    '(569) 787-4157',
    '2021-12-22',
    'Senior Product Engineer',
    140000,
    2
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '3d6954b22c342dbea6449220307e3c71051542eb1fdb3e0d6b1f4a035ac5aa11',
    0,
    'Mariah Haynes',
    'mariahh@waldoshoes.com',
    '(963) 908-5999',
    '2021-12-28',
    'Product Researcher',
    95000,
    5
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    'fadb6e3d470e377aff6d2b3ac541befa86dde3598192868494763559221ac3d7',
    0,
    'Lorena Tolbert',
    'lorenat@waldoshoes.com',
    '(420) 375-8558',
    '2021-12-28',
    'Product Researcher',
    95000,
    5
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '99ce2e425f767558d7926fa80e2761f9c7e4fd832be5f4fb93a566486a47a543',
    0,
    'Cori Scarlett',
    'coris@waldoshoes.com',
    '(481) 084-7603',
    '2021-12-21',
    'Product Engineer',
    12000,
    2
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '98a797a033b01f70340e6c52f4a0cb8675b869c1d8fd1e9e583a936463501def',
    0,
    'Edison Ashley',
    'edisona@waldoshoes.com',
    '(660) 591-9369',
    '2021-12-21',
    'Product Engineer',
    12000,
    2
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '8365cd249922edaefc3a033cfbb92e77df7f752a83d5d6750f1ba3eec8961678',
    0,
    'Maryann Taylor',
    'maryannt@waldoshoes.com',
    '(405) 986-5893',
    '2021-12-16',
    'Salesperson',
    40000,
    3
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '605aa04f14921baa97f0c9e9d465b694d42a96c89f2f439ba90409c39fcb367f',
    0,
    'Phyllis Gary',
    'phyllisg@waldoshoes.com',
    '(982) 184-3036',
    '2021-12-16',
    'Salesperson',
    40000,
    3
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '755231f5e11e27d9e00fa7cdd110891e2992f862ee6e68553d297ff64f0f9431',
    0,
    'Darwin Lowell',
    'darwinl@waldoshoes.com',
    '(931) 423-7461',
    '2021-12-16',
    'Salesperson',
    40000,
    3
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '5f4ec7029a50b3a2371ff80bc3d4cf0aef830abb1d681cbcf3a6a3cf7bd63835',
    0,
    'Archibald Moores',
    'archibaldm@waldoshoes.com',
    '(850) 244-2838',
    '2021-12-16',
    'Salesperson',
    40000,
    3
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '333d83f58f6c5324322c838f35fec366f1b3e8b1212ba317fb76b2c7ad661c70',
    0,
    'Alvina Wade',
    'alvinaw@waldoshoes.com',
    '(895) 766-0209',
    '2021-12-23',
    'Computer Technician',
    200000,
    4
);

INSERT INTO employees (
    salted_hash, permission, name, email,
    phone_number, hire_date, position,
    salary, manager_id
) VALUES (
    '9c6d4a4c107de8b807d7883d98638495f15a5e0689a870bfd4a57dc7f08c828f',
    0,
    'Thaddeus Carl',
    'thaddeusc@waldoshoes.com',
    '(545) 123-8153',
    '2021-12-23',
    'Computer Technician',
    200000,
    4
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Running Shoes (Black)',
    155,
    80,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Running Shoes (White)',
    155,
    97,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Running Shoes (Brown)',
    155,
    31,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Running Shoes (Blue)',
    155,
    39,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sandals (Black)',
    455,
    23,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sandals (White)',
    455,
    58,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sandals (Brown)',
    455,
    51,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sandals (Blue)',
    455,
    62,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sneakers (Black)',
    290,
    69,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sneakers (White)',
    290,
    98,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sneakers (Brown)',
    290,
    64,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Sneakers (Blue)',
    290,
    70,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Long Boots (Black)',
    323,
    30,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Long Boots (White)',
    323,
    92,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Long Boots (Brown)',
    323,
    98,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Long Boots (Blue)',
    323,
    52,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Flip Flops (Black)',
    214,
    94,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Flip Flops (White)',
    214,
    62,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Flip Flops (Brown)',
    214,
    71,
    0
);

INSERT INTO products (
    name,
    price,
    stock,
    is_deleted
) VALUES (
    'Flip Flops (Blue)',
    214,
    69,
    0
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-18',
    '08:14:54',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-18',
    '08:50:42',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-18',
    '12:23:07',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-18',
    '16:06:26',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-18',
    '17:08:52',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-19',
    '08:03:59',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-19',
    '11:18:25',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-19',
    '15:11:21',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-19',
    '20:21:09',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-20',
    '10:42:21',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-20',
    '21:06:53',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-21',
    '09:54:43',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-21',
    '10:35:35',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-21',
    '15:14:15',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-22',
    '08:07:18',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-22',
    '17:23:06',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-22',
    '22:36:37',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-23',
    '17:06:06',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-23',
    '19:58:43',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-23',
    '21:00:46',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-23',
    '21:35:36',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-24',
    '08:40:32',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-24',
    '12:13:15',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2021-12-24',
    '16:15:02',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-01',
    '08:40:14',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-01',
    '09:49:07',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-01',
    '12:48:23',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-01',
    '17:06:39',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-01',
    '19:19:21',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-02',
    '09:46:14',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-02',
    '09:49:25',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-02',
    '12:40:11',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-02',
    '16:32:12',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-02',
    '17:52:54',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-02',
    '22:56:17',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-03',
    '09:58:06',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-03',
    '10:02:17',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-03',
    '10:29:47',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-03',
    '18:22:50',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-03',
    '19:16:01',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-04',
    '12:21:44',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-04',
    '16:55:17',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-04',
    '19:49:20',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-04',
    '20:21:20',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-05',
    '14:11:41',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-05',
    '20:26:19',
    13
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-06',
    '14:45:39',
    11
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-06',
    '22:57:36',
    12
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-07',
    '11:01:38',
    10
);

INSERT INTO sales (date, time, cashier_id) VALUES (
    '2022-01-07',
    '11:21:52',
    10
);
INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    1,
    4,
    4
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    2,
    2,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    2,
    8,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    2,
    11,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    3,
    4,
    6
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    4,
    16,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    4,
    14,
    4
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    5,
    15,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    5,
    12,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    5,
    9,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    5,
    6,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    6,
    2,
    9
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    7,
    6,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    7,
    20,
    5
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    8,
    13,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    8,
    2,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    8,
    16,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    9,
    9,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    9,
    3,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    9,
    2,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    10,
    19,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    10,
    14,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    10,
    13,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    10,
    8,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    11,
    3,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    11,
    10,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    11,
    17,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    12,
    11,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    12,
    10,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    12,
    17,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    13,
    3,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    14,
    17,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    14,
    14,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    14,
    4,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    15,
    16,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    15,
    1,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    16,
    10,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    16,
    17,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    16,
    1,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    16,
    2,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    16,
    5,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    17,
    5,
    8
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    18,
    12,
    10
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    19,
    16,
    4
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    19,
    2,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    20,
    9,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    20,
    4,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    20,
    6,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    20,
    10,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    21,
    19,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    21,
    12,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    21,
    7,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    21,
    15,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    22,
    7,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    22,
    12,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    22,
    13,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    22,
    11,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    23,
    10,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    23,
    6,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    23,
    13,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    24,
    4,
    9
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    25,
    19,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    25,
    3,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    25,
    6,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    26,
    15,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    26,
    8,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    26,
    14,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    27,
    2,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    27,
    16,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    27,
    5,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    27,
    9,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    28,
    12,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    28,
    11,
    5
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    29,
    20,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    29,
    5,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    29,
    2,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    29,
    18,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    30,
    16,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    30,
    11,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    31,
    9,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    31,
    11,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    31,
    6,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    31,
    19,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    31,
    3,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    32,
    16,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    32,
    11,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    32,
    19,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    33,
    7,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    33,
    11,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    33,
    8,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    34,
    3,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    35,
    10,
    8
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    36,
    2,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    36,
    7,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    36,
    12,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    36,
    4,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    37,
    1,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    37,
    8,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    37,
    20,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    37,
    6,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    38,
    18,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    39,
    4,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    39,
    11,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    39,
    9,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    40,
    5,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    40,
    7,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    40,
    2,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    41,
    11,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    41,
    9,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    41,
    8,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    42,
    16,
    9
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    43,
    11,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    43,
    17,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    43,
    15,
    3
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    44,
    13,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    44,
    2,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    44,
    12,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    45,
    6,
    7
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    46,
    17,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    46,
    16,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    47,
    18,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    47,
    15,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    47,
    6,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    47,
    20,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    47,
    16,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    48,
    19,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    48,
    1,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    48,
    8,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    48,
    3,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    49,
    7,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    49,
    3,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    49,
    1,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    49,
    13,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    50,
    10,
    1
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    50,
    2,
    2
);

INSERT INTO sales_products (
    sale_id,
    product_id,
    quantity_sold
) VALUES (
    50,
    9,
    3
);

COMMIT;
